<?php

namespace Dalilak\VenueBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * VenueRepository
 * 
 * @author Alaa Attya <alaa.attya91@gmail.com> 
 * @package Dalilak.VenueBundle.Repository
 * @version 1.0
 * @license  http://www.opensource.org/licenses/mit-license.php The MIT License
 * @category Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VenueRepository extends EntityRepository {

    /**
     * Get Venues by category alias
     * 
     * @param string $category_alias
     */
    public function getByCategoryAlias($category_alias) {
        $q = $this->createQueryBuilder('venue');
        return $q->innerJoin("venue.categories", "c")
                        ->where(
                                $q->expr()->like('c.alias', ':category_alias')
                        )->setParameter('category_alias', "%$category_alias%")
                        ->getQuery()
                        ->getResult();
    }

}
